### OBTIENE TODAS LAS BETS ####
GET http://localhost:1234/bet/

### TODAS LAS BETS DE UN USUARIO POR ID####
GET http://localhost:1234/bet/user/
Content-Type: application/json

{
  "id_user": "9cd4cc71-20fd-486f-a487-261c09daf30a"
}

#### GET BET POR ID###
GET http://localhost:1234/bet/id
Content-Type: application/json

{
  "id_bet": "9cd4cc71-20fd-486f-a487-261c09daf30a"
}

#### CREA UNA APUESTA ###
POST http://localhost:1234/bet/
Content-Type: application/json

{
  "id_user" :"34d28724-9217-4f7e-ab37-f4a3bac1b6b1",
  "id_event": "604323c1-043f-4523-93a9-7340b34bbfd5",
  "category": "1 A 1",
  "type": "GANADOR",
  "amount": 10000,
  "extra": 1.5
}
### ACEPTAR UNA APUESTA ###
PATCH http://localhost:1234/bet/place
Content-Type: application/json

{
  "id_bet": "0c2f6d95-d740-4975-9588-9c153a6099da",
  "id_user": "53a28e31-8624-4572-9f73-6915e06e04a0"
}

### Busqueda por parametros en general search
GET http://localhost:1234/bet/search?id_user=53a28e31-8624-4572-9f73-6915e06e04a0

### Busqueda por parametros en general search
GET http://localhost:1234/bet/search?status=EN PROCESO

