### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=WebStorm


###
POST http://localhost:1234/bonus/
Content-Type: application/json

{
  "amount": 25,
  "type": "bienvenida"
}

###
GET http://localhost:1234/bonus/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoiYjA0Y2QwM2ItMGU1Yy00ZTczLTkxNTItYTNkMGEyMDA0N2QxIiwidXNlcm5hbWUiOiJHaWxiZXJ0byBBdmFsb3MiLCJyb2wiOiJBRE1JTiIsImlhdCI6MTc0NjMwOTkzNSwiZXhwIjoxNzQ2MzEzNTM1fQ.IzPxASLES4U24kL7Faecekru2LvHltWTlIWlyi_S03E




###
POST http://localhost:1234/bonus/redeem/cf48d381-41e2-47f5-bbe7-6992597d4304
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoiYjA0Y2QwM2ItMGU1Yy00ZTczLTkxNTItYTNkMGEyMDA0N2QxIiwidXNlcm5hbWUiOiJHaWxiZXJ0byBBdmFsb3MiLCJyb2wiOiJBRE1JTiIsImlhdCI6MTc0NjMwOTkzNSwiZXhwIjoxNzQ2MzEzNTM1fQ.IzPxASLES4U24kL7Faecekru2LvHltWTlIWlyi_S03E
