### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=WebStorm

### SOLICITUD PARA CREAR UNA APUESTA
// "name" debe ser de la siguiente forma "equipoA vs equipoB" el vs debe ir en medio separado de un espacio y sport
// debe se alguno de los que estan en const.js en CATEGORY
POST http://localhost:1234/event/
Content-Type: application/json

{
  "name": "vikings vs lakers",
  "sport": "basquetbol"
}
### EJEMPLO DE CREAR APUESTA/EVENTO 1 VS 1
// Para crear una apuesta de tipo 1vs 1 tenemos que poner en sport el evento que seria 1 vs 1 y luego el deporte del que es
POST http://localhost:1234/event/
Content-Type: application/json

{
  "name": "Chivas vs america",
  "sport": "1 vs 1 futbol",
  "outcomes": [
    { "outcome_name": "ganador", "official_odds": 1 },
    { "outcome_name": "goles", "official_odds": 1 },
    { "outcome_name": "tarjetas amarillas", "official_odds": 1 },
    { "outcome_name": "tiros esquina", "official_odds": 1 },
    { "outcome_name": "tarjetas rojas", "official_odds": 1 }
  ]
}

### CON ESTA SOLICITUD SE ACTUALIZAN LAS ESTADISTICAS DE UN PARTIDO (futbol)
// type debe ser el mismo que el del evento que se creo y se necesita el id_event
// este es para el ejemplo de que sea futbol porque sus campos son para partido de futbol(independientemente de si es 1 vs 1 o normal)
PATCH http://localhost:1234/sports
Content-Type: application/json

{
  "type": "futbol",
  "id_event": "8315ff0c-da7f-4638-83fd-a5d50fd89e43",
  "data": {
    "home_goals": 4,
    "away_goals": 1,
    "yellow_cards": 3,
    "red_cards": 1,
    "corners": 1,
    "penalties": 1
  }
}

### Cerrar un evento
PATCH http://localhost:1234/event/close
Content-Type:  application/json

{
  "id_event": "8315ff0c-da7f-4638-83fd-a5d50fd89e43",
  "result": "pendiente"
}

### Cerrar un evento
PATCH http://localhost:1234/event/close
Content-Type:  application/json

{
  "id_event": "72547eca-6fe7-48c7-bb92-ed37697205fc",
  "result": "pendiente"
}


### Cerrar un evento
PATCH http://localhost:1234/event/close
Content-Type:  application/json

{
  "id_event": "39793f32-dab1-4393-907d-5e425b0e400d",
  "result": "pendiente"
}



### Buscar evento por ID
GET http://localhost:1234/event/3d5842f5-8e24-4510-9ba9-7b8a24b4bfcd

### Buscar por cualquier tipo de parametros de la consulta
//estas solicitudes son para buscar por cualquier filtro de la forma especificada
GET http://localhost:1234/event/search?name=america vs chivas

###
GET http://localhost:1234/event

###
GET http://localhost:1234/event/search?id_event=c01aad56-3d86-486e-bff2-5abb1e728f4e


////////////////////////////////////////////////////////////////////
//EJEMPLOS PARA ACTUALIZAR PARTIDOS DE BASQUETBOL Y FUTBOL AMERICANO
////////////////////////////////////////////////////////////////////

### basquetbol
PATCH http://localhost:1234/sports
Content-Type: application/json

{
"type": "basquetbol",
"id_event": "72547eca-6fe7-48c7-bb92-ed37697205fc",
"data": {
"home_points": 5,
"away_points": 3,
"three_pointers": 4,
"fouls": 1,
"rebounds": 5
}
}

### futbol americano
PATCH http://localhost:1234/sports
Content-Type: application/json

{
  "type": "futbol americano",
  "id_event": "4f35483d-63fd-4391-a7ae-63a3ef490170",
  "data": {
    "home_touchdowns": 5,
    "away_touchdowns": 1,
    "field_goals": 4,
    "interceptions": 3,
    "sacks": 5
  }
}

### GET
http://localhost:1234/event/c01aad56-3d86-486e-bff2-5abb1e728f4e/outcomes


###
PATCH http://localhost:1234/event/outcomes/9fefd906-598c-4297-8925-86e92b7ed86d
Content-Type: application/json

{
"official_odds": 3.45
}

###
PATCH http://localhost:1234/event/5afc2581-820a-4ff7-83f1-82a3835c208f
Content-Type: application/json

{
  "name": "Chihuahua vs Queretaro",
  "sport": "futbol",
  "status": "en proceso"
}

###
DELETE http://localhost:1234/event/7be32d4f-2b0d-4b70-b480-82ab821a3acf

